services:
  app:
    build: ./backend
    container_name: api.steprun.ai
    env_file:
      - ${APP_ENV_FILE:-./backend/.env.prod}
    environment:
      POSTGRES_SERVER: pg
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-steprun}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - sandboxes:/sandboxes
    expose:
      - "8000"
    depends_on:
      pg:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - steprun_network

  frontend:
    build: ./frontend
    container_name: steprun.ai
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - steprun_network

  pg:
    image: bitnami/postgresql:15
    container_name: postgres.steprun.ai
    environment:
      # POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_DATABASE: ${POSTGRES_DB:-steprun}
    volumes:
      - postgres_data:/bitnami/postgresql
    expose:
      - "5432"
    networks:
      - steprun_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf
      - ../docker/certs:/etc/nginx/certs
    depends_on:
      - app
      - frontend
    restart: unless-stopped
    networks:
      - steprun_network

volumes:
  sandboxes:
  postgres_data:

networks:
  steprun_network:
    driver: bridge