services:
  app:
    build: ./backend
    container_name: api.steprun.ai
    networks:
      - steprun_private
    env_file:
      - ${APP_ENV_FILE:-.env.prod}
    user: root
    environment:
      POSTGRES_SERVER: pg
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-steprun}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - sandboxes:/sandboxes
    expose:
      - "8000"
    depends_on:
      - pg

  frontend:
    build: ./frontend
    container_name: steprun.ai
    expose:
      - "3000"
    networks:
      - steprun_network
    environment:
      - NODE_ENV=production

  pg:
    image: bitnami/postgresql:15
    networks:
      - steprun_private
    container_name: postgres.steprun.ai
    environment:
      # POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_DATABASE: ${POSTGRES_DB:-steprun}
      POSTGRESQL_PG_NETWORK_MASK: 172.0.0.0/8
    volumes:
      - postgres_data:/bitnami/postgresql
    expose:
      - "5432"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - frontend
    networks:
      - steprun_private

volumes:
  sandboxes:
  postgres_data:

networks:
  steprun_private:
    driver: bridge