services:
  app:
    build: .
    env_file:
      - ${APP_ENV_FILE:-.env.prod}
    container_name: api.steprun.ai
    environment:
      POSTGRES_SERVER: pg
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-steprun}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - sandboxes:/sandboxes
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 30s
      timeout: 10s
      retries: 3

  pg:
    image: bitnami/postgresql:15
    container_name: postgres.steprun.ai
    environment:
      # POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_DATABASE: ${POSTGRES_DB:-steprun}
    volumes:
      - postgres_data:/bitnami/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sandboxes:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /mydata/steprun/sandboxes
  postgres_data: