services:
  app:
    build: .
    container_name: api.steprun.ai
    networks:
      - steprun_private
      - default
    env_file:
      - ${APP_ENV_FILE:-.env.prod}
    user: root
    environment:
      POSTGRES_SERVER: pg
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-steprun}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - sandboxes:/sandboxes
    ports:
      - "8000:8000"
    depends_on:
      - pg

  pg:
    image: bitnami/postgresql:15
    networks:
      - steprun_private
    container_name: postgres.steprun.ai
    environment:
      # POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_DATABASE: ${POSTGRES_DB:-steprun}
      POSTGRESQL_PG_NETWORK_MASK: 172.0.0.0/8
    volumes:
      - postgres_data:/bitnami/postgresql
    # ports:
    #   - "5432:5432"

volumes:
  sandboxes:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /mydata/steprun/sandboxes
  postgres_data:

networks:
  steprun_private:
    driver: bridge
    internal: true
  default:
    driver: bridge