version: "3.9"

services:
  app:
    build: .
    container_name: api.steprun.ai
    user: root
    volumes:
      - sandboxes:/sandboxes
    ports:
      - "8000:8000"

volumes:
  sandboxes:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /mydata/steprun/sandboxes
