"""user-session

Revision ID: 345bf7849635
Revises: cfd4a370879b
Create Date: 2025-05-15 18:11:50.018589

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '345bf7849635'
down_revision = 'cfd4a370879b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersession',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at_brin', 'usersession', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index(op.f('ix_usersession_created_at'), 'usersession', ['created_at'], unique=False)
    op.create_index(op.f('ix_usersession_session_id'), 'usersession', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersession_session_id'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_created_at'), table_name='usersession')
    op.drop_index('idx_created_at_brin', table_name='usersession', postgresql_using='brin')
    op.drop_table('usersession')
    # ### end Alembic commands ###
