"""user_session.status

Revision ID: 3b7903645bd3
Revises: 345bf7849635
Create Date: 2025-05-20 10:25:43.615030

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b7903645bd3'
down_revision = '345bf7849635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    sa.Enum('STARTED', 'STOPPED', 'HIBERNATED', 'DESTROYED', name='sessionstatus').create(op.get_bind())

    op.add_column(
        "usersession",
        sa.Column(
            "status",
            sa.Enum(
                "STARTED", "STOPPED", "HIBERNATED", "DESTROYED", name="sessionstatus"
            ),
            nullable=False,
            server_default="STARTED",
        ),
    )
    op.drop_column("usersession", "is_active")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersession', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('usersession', 'status')

    # Then drop the enum type
    op.execute('DROP TYPE sessionstatus')
    # ### end Alembic commands ###
