"""user.created_at

Revision ID: 8197eafb4dd9
Revises: 3b7903645bd3
Create Date: 2025-05-21 08:06:40.957495

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "8197eafb4dd9"
down_revision = "3b7903645bd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index(op.f("ix_user_created_at"), "user", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_created_at"), table_name="user")
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###
