"""apikey

Revision ID: cfd4a370879b
Revises: 1a31ce608336
Create Date: 2025-05-15 14:01:05.712088

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cfd4a370879b'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandboxusage',
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('api_key_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cost_units', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandboxusage_id'), 'sandboxusage', ['id'], unique=False)
    op.create_index(op.f('ix_sandboxusage_user_id'), 'sandboxusage', ['user_id'], unique=False)
    op.add_column('user', sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_api_key'), 'user', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_key'), table_name='user')
    op.drop_column('user', 'api_key')
    op.drop_index(op.f('ix_sandboxusage_user_id'), table_name='sandboxusage')
    op.drop_index(op.f('ix_sandboxusage_id'), table_name='sandboxusage')
    op.drop_table('sandboxusage')
    # ### end Alembic commands ###
